/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ClassInfo {
  name: string
  namespace: string
  address: number
  isStatic: boolean
  isEnum: boolean
}
export interface FieldInfo {
  name: string
  typeName: string
  offset: number
  isStatic: boolean
  isConst: boolean
}
export interface StaticInstanceInfo {
  fieldName: string
  address: number
}
export interface ClassDetails {
  name: string
  namespace: string
  address: number
  fields: Array<FieldInfo>
  staticInstances: Array<StaticInstanceInfo>
}
export interface InstanceField {
  name: string
  typeName: string
  isStatic: boolean
  value: any
}
export interface InstanceData {
  className: string
  namespace: string
  address: number
  fields: Array<InstanceField>
}
export interface DictionaryEntry {
  key: any
  value: any
}
export interface DictionaryData {
  count: number
  entries: Array<DictionaryEntry>
}
export declare function isAdmin(): boolean
export declare function findProcess(processName: string): boolean
export declare function init(processName: string): boolean
export declare function close(): boolean
export declare function isInitialized(): boolean
export declare function getAssemblies(): Array<string>
export declare function getAssemblyClasses(assemblyName: string): Array<ClassInfo>
export declare function getClassDetails(assemblyName: string, className: string): ClassDetails
export declare function getInstance(address: number): InstanceData
export declare function getInstanceField(address: number, fieldName: string): any
export declare function getStaticField(classAddress: number, fieldName: string): any
export declare function getDictionary(address: number): DictionaryData
export declare function readData(processName: string, fields: Array<string>): any
/**
 * Signature-based card-collection reader. Scans the MTGA process
 * heap for a `Dictionary<int, int>` object whose contents match
 * the shape of an Arena player collection (enough entries, keys in
 * the Arena card-id range, values in the quantity range) and
 * returns the list of (cardId, quantity) entries.
 *
 * This is a macOS-only path added as a local patch: the
 * `readData` walker starting from PAPA / WrapperController turned
 * out to be too fragile against current Arena builds (IL2CPP
 * metadata layout drift, runtime-class-vs-metadata-class
 * indirection, inconsistent CLASS_NAME offsets on runtime-allocated
 * class structs). The signature scan sidesteps every one of those
 * by searching for the only dictionary in the process whose entries
 * all look like real card entries.
 *
 * Returns a JSON array of `{ "cardId": int, "quantity": int }`
 * objects on success, or `{ "error": string }` on any failure.
 */
export declare function readMtgaCards(processName: string): any
export declare function readClass(processName: string, address: number): any
export declare function readGenericInstance(processName: string, address: number): any
